package calcul;


/**
* calcul/calcul_montants.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from spec.idl
* mardi 7 décembre 2021 23 h 28 WAT
*/

public interface calcul_montants extends calcul_montantsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calcul_montants
