package exo1;


/**
* exo1/calculOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Tuesday, 7 December 2021 18:40:24 o'clock WAT
*/

public interface calculOperations 
{
  void incrementer (org.omg.CORBA.IntHolder data);
  void decrementer (org.omg.CORBA.IntHolder data);
} // interface calculOperations
