package exo1;


/**
* exo1/calcul.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Tuesday, 7 December 2021 18:40:24 o'clock WAT
*/

public interface calcul extends calculOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calcul
